routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', ['as' => 'login', 'uses' => 'Auth\LoginController@getLogin']);
Route::post('/login',           'Auth\LoginController@postLogin');
Route::any('/logout',           'Auth\LoginController@anyLogout');

Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::group(['middleware' => ['auth']], function()
{
	Route::get('/', 'DashboardController@getHome');
	Route::get('/my-profile', 'UserController@getProfile');
    Route::post('/my-profile/password', 'UserController@postProfilePassword');
});

Route::group(['middleware' => ['auth', 'group:provider']], function()
{
	Route::get('/individual/view/{id}', 'IndividualController@getViewIndividual');
	Route::get('/individual/casenote/{id}/add', 'IndividualController@getAddCaseNote');
	Route::post('/individual/casenote/{id}/add', 'IndividualController@postAddCaseNote');
	Route::get('/individual/casenote/{id}/edit/{cn_id}', 'IndividualController@getEditCaseNote');
	Route::post('/individual/casenote/{id}/edit/{cn_id}', 'IndividualController@postEditCaseNote');
	Route::get('/individual/medication/{id}/take/{med}', 'IndividualController@getTakeMedication');

	Route::get('/training/list','TrainingController@getTrainingList');
	Route::get('/training/take/{id}', 'TrainingController@getTrainingTake');
    Route::post('/training/take/{id}', 'TrainingController@postTrainingTake');
    
    Route::get('/clock/{punch}/{user_id?}', 'UserController@getClockInOut');

    Route::get('/house/schedule/{id}', 'HouseController@getHouseSchedule');
});

Route::group(['middleware' => ['auth', 'groupType:provider|Administrator;provider|Manager']], function()
{
	
	Route::get('/user/profile/{id}', 'UserController@getProfile');
	Route::get('/user/list', 'UserController@getUserList');
	Route::get('/user/add', 'UserController@getAddUser');
	Route::post('/user/add', 'UserController@postAddUser');
	Route::get('/user/edit/{id}', 'UserController@getEditUser');
    Route::post('/user/edit/{id}', 'UserController@postEditUser');
    Route::get('/user/remove/{id}', 'UserController@getRemoveUser');

    //user files
    Route::post('/user/file/{id}', 'UserController@postFileUser');
    Route::get('/user/file/{id}/remove/{ur_id}', 'UserController@getRemoveUserFileUpload');

	Route::get('/user/permission/{id}', 'UserController@getAddUserPermission');
	Route::post('/user/permission/{id}', 'UserController@postAddUserPermission');
	Route::get('/user/permission/{id}/remove/{ur_id}', 'UserController@getRemoveUserPermission');
	
	Route::post('/user/edit/{id}/house', 'UserController@postEditUserHouse');
	
	Route::get('/house/list', 'HouseController@getHouseList');
	Route::get('/house/add', 'HouseController@getAddHouse');
	Route::post('/house/add', 'HouseController@postAddHouse');
	Route::get('/house/edit/{id}', 'HouseController@getEditHouse');
	Route::post('/house/edit/{id}', 'HouseController@postEditHouse');
	Route::get('/house/view/{id}', 'HouseController@getViewHouse');
	Route::get('/house/safety-checklist/{id}/add', 'FormController@getSafetyChecklistAdd');
	Route::post('/house/safety-checklist/{id}/add', 'FormController@postSafetyChecklistAdd');
	Route::get('/house/safety-checklist/{id}/edit/{checklist_id}', 'FormController@getSafetyChecklistEdit');
	Route::post('/house/safety-checklist/{id}/edit/{checklist_id}', 'FormController@postSafetyChecklistAdd');
	Route::get('/house/safety-checklist/{id}/view/{checklist_id}', 'FormController@getSafetyChecklistView');	
	Route::get('/house/safety-checklist/{id}/remove/{checklist_id}', 'FormController@getSafetyChecklistRemove');	

    
	
	Route::get('/individual/list', 'IndividualController@getIndividualList');
	Route::get('/individual/add', 'IndividualController@getAddIndividual');
	Route::post('/individual/add', 'IndividualController@postAddIndividual');
	Route::get('/individual/edit/{id}', 'IndividualController@getEditIndividual');
	Route::post('/individual/edit/{id}', 'IndividualController@postEditIndividual');
	//edit/add house
	Route::post('/individual/edit/{id}/house', 'IndividualController@postEditIndividualHouse');
	
	Route::get('/individual/casenote/{id}/list', 'IndividualController@getListCaseNote');
	
	//medication for individual
	Route::get('/individual/medication/{id}/view', 'IndividualController@getViewMedication');
	Route::post('/individual/medication/{id}/add', 'IndividualController@postAddMedication');
	Route::get('/individual/medication/{id}/remove/{med}', 'IndividualController@getRemoveMedication');
	Route::get('/individual/medication/{id}/taken-report', 'IndividualController@getTakenMedication');
	Route::get('/individual/medication/{id}/remove/{med}/{med_taken_id}', 'IndividualController@getRemoveTakenMedication');
	
	//medical appointments
	Route::get('/individual/medical-appointment/{id}/add', 'IndividualController@getMedicalAppointmentAdd');
	Route::post('/individual/medical-appointment/{id}/add', 'IndividualController@postMedicalAppointmentAdd');
	Route::get('/individual/medical-appointment/{id}/edit/{apointment_id}', 'IndividualController@getMedicalAppointmentEdit');
	Route::post('/individual/medical-appointment/{id}/edit/{apointment_id}', 'IndividualController@postMedicalAppointmentAdd');
	Route::get('/individual/medical-appointment/{id}/view/{apointment_id}', 'IndividualController@getMedicalAppointmentView');
	Route::get('/individual/medical-appointment/{id}/remove/{apointment_id}', 'IndividualController@getMedicalAppointmentRemove');

	//support team
	Route::get('/individual/support-team/{id}/add', 'IndividualController@getSupportTeamAdd');
	Route::post('/individual/support-team/{id}/add', 'IndividualController@postSupportTeamAdd');
	Route::get('/individual/support-team/{id}/edit/{member_id}', 'IndividualController@getSupportTeamEdit');
	Route::post('/individual/support-team/{id}/edit/{member_id}', 'IndividualController@postSupportTeamAdd');
	Route::get('/individual/support-team/{id}/view/{member_id}', 'IndividualController@getSupportTeamView');
	Route::get('/individual/support-team/{id}/remove/{member_id}', 'IndividualController@getSupportTeamRemove');
	//suport team concerns
	Route::post('/individual/support-team/{id}/view/{member_id}', 'IndividualController@postSupportTeamConcernAdd');
	Route::get('/individual/team-concern/{id}/remove/{concern_id}', 'IndividualController@getSupportTeamConcernRemove');

	//seizure
	Route::get('/individual/seizures/{id}/add', 'IndividualController@getSeizuresAdd');
	Route::post('/individual/seizures/{id}/add', 'IndividualController@postSeizuresAdd');
	Route::get('/individual/seizures/{id}/edit/{seizure_id}', 'IndividualController@getSeizuresEdit');
	Route::post('/individual/seizures/{id}/edit/{seizure_id}', 'IndividualController@postSeizuresAdd');
	Route::get('/individual/seizures/{id}/view/{seizure_id}', 'IndividualController@getSeizuresView');
	Route::get('/individual/seizures/{id}/remove/{seizure_id}', 'IndividualController@getSeizuresRemove');

	//risk plans
	Route::get('/individual/risk-plan/{id}/add', 'IndividualController@getRiskPlanAdd');
	Route::post('/individual/risk-plan/{id}/add', 'IndividualController@postRiskPlanAdd');
	Route::get('/individual/risk-plan/{id}/edit/{seizure_id}', 'IndividualController@getRiskPlanEdit');
	Route::post('/individual/risk-plan/{id}/edit/{seizure_id}', 'IndividualController@postRiskPlanAdd');
	Route::get('/individual/risk-plan/{id}/remove/{seizure_id}', 'IndividualController@getRiskPlanRemove');

	//goals for individual
	Route::get('/individual/goal/{id}/view', 'IndividualController@getViewGoal');
	Route::post('/individual/goal/{id}/add', 'IndividualController@postAddGoal');
	Route::post('/individual/goal/{id}/strategy', 'IndividualController@postAddStrategy');
    Route::get('/individual/goal/{id}/remove/{goal_id}', 'IndividualController@getRemoveGoal');
    
    //note approval/reject
    Route::get('/individual/casenote/{id}/approve/{cn_id}', 'IndividualController@getCaseNoteApproval');    
    Route::get('/individual/casenote/{id}/reject/{cn_id}', 'IndividualController@getCaseNoteReject');
    Route::post('/individual/casenote/{id}/reject/{cn_id}', 'IndividualController@postCaseNoteReject');
    Route::get('/individual/casenote/{id}/unapprove/{cn_id}', 'IndividualController@getCaseNoteUnApprove');
	
	//Reports
	Route::get('/provider/report/case-notes/minor', 'ReportController@getMinorIncidentNote');
	Route::get('/provider/report/case-notes/major', 'ReportController@getMajorIncidentNote');
	Route::get('/provider/report/case-notes/by-individual', 'ReportController@getIndividualNote');
	Route::get('/provider/report/case-notes/with-qol', 'ReportController@getQolNote');
	Route::get('/provider/report/case-notes/approval', 'ReportController@getIndividualNoteApproval');
	Route::get('/provider/report/case-notes/approved', 'ReportController@getIndividualNoteApproved');
	Route::get('/provider/report/employee-list', 'ReportController@getEmployeeList');
	Route::get('/provider/report/medication/by-individual', 'ReportController@getMedicationByIndividual');
	Route::get('/provider/report/medication/missed-by-time', 'ReportController@getMissedMedicationByTime');
	Route::get('/provider/report/training/by-employee', 'ReportController@getTrainingByEmployee');

app/Models/ProviderHouse.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class ProviderHouse extends Model
{
	use SoftDeletes;
	
	protected $table = 'tblProviderHouse';
	
	protected $dates = ['created_at', 'updated_at', 'deleted_at'];
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */	
    protected $fillable = [
		'provider_id', 'nickname', 'address', 'city', 'state', 'zip', 'phone'
    ];

    protected $guarded = [];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
       
    ];
	
	public function employees()
    {
        return $this->belongsToMany('App\Models\User', 'tblProviderHouseUser', 'house_id', 'user_id')->whereNull('tblProviderHouseUser.deleted_at');
    }
	
	public function individuals()
    {
        return $this->belongsToMany('App\Models\ProviderIndividual', 'tblProviderHouseIndividual', 'house_id', 'individual_id')->whereNull('tblProviderHouseIndividual.deleted_at');
    }
	
	public function individuals_with_casenotes()
    {
        return $this->belongsToMany('App\Models\ProviderIndividual', 'tblProviderHouseIndividual', 'house_id', 'individual_id')->whereNull('tblProviderHouseIndividual.deleted_at')->with('casenotes');
    }
	
	public function individuals_with_today_user_case_note()
    {
        return $this->belongsToMany('App\Models\ProviderIndividual', 'tblProviderHouseIndividual', 'house_id', 'individual_id')->whereNull('tblProviderHouseIndividual.deleted_at')->with('casenote_today_current_user');
    }

    public function safety_checklists()
	{
		return $this->hasMany('App\Models\ProviderHouseFormSafetyChecklist', 'house_id', 'id')->orderBy('drill_date', 'DESC');
	}
	
	public function getAddressBlockAttribute()
	{
		return "{$this->address} " . "{$this->city} " . "{$this->state}, " . "{$this->zip}";
	}
}

resources/views/home.blade.php
@extends('layouts.master.master')

@section('title', 'Home')


@section('content')
    <!-- begin #content -->
	<div id="content" class="content">
		
		<!-- begin page-header -->
		<h1 class="page-header">Home <small>Compliance Documentor</small></h1>
		<!-- end page-header -->
		
		@include('includes.error.list')
		
		<div class="row">
			@if(Auth::user()->hasGroupType('provider', ['Administrator', 'Manager', 'Supervisor']))
			<div class="col-md-12">
				<div class="panel panel-danger">
					<div class="panel-heading">
						<h4 class="panel-title">Missed Medication</h4>
					</div>
					<div class="panel-body">
						@foreach($houses AS $house)
							@foreach($house->individuals AS $individual)
								@if($individual->missed->count() > 0)
									<div class="row">
										<div class="col-sm-6 col-md-1">
										<a class="btn btn-xs btn-success" href="./individual/view/{{encrypt($individual->id)}}"><i class="fa fa-eye"></i></a> {{$individual->full_name}}
										</div>
										<div class="col-sm-6 col-md-11">
											@foreach($individual->missed AS $miss)
												{{$miss['medication']['name']}} - {{$miss['time']}}<br />
											@endforeach
										</div>
									</div>
									<hr>
								@endif
							@endforeach
						@endforeach
					</div>
				</div>
			</div>
			@endif
            @if($rejected_notes->count() > 0)
            <div class="col-md-12">
				<div class="panel panel-warning">
					<div class="panel-heading">
						<h4 class="panel-title">Rejected Service Notes</h4>
					</div>
					<div class="panel-body">
							@foreach($rejected_notes AS $case_note)
                                <div class="row p-5">
                                    <div class="col-sm-1 col-md-1">
                                    <a class="btn btn-xs btn-warning" href="./individual/casenote/{{encrypt($case_note->individual_id)}}/edit/{{encrypt($case_note->id)}}">Fix</i></a> 
                                    </div>
                                    <div class="col-sm-1 col-md-1">
                                        <p>{{$case_note->individual->full_name}}</p>
                                    </div>
                                    <div class="col-sm-5 col-md-5">
                                        <p>Sent back on: <strong>{{$case_note->reject_date}}</strong></p>
                                    </div>
                                    <div class="col-sm-5 col-md-5">
                                        <p>
                                        {{ nl2br($case_note->reject_note)}}
                                        </p>
                                    </div>
                                </div>
                                <hr>
						@endforeach
					</div>
				</div>
			</div>
            @endif
			<div class="col-md-12">
				<!-- begin panel -->
				
				@foreach($user->current_houses AS $k => $house)
					<div class="panel panel-success">
						<div class="panel-heading">
							<h4 class="panel-title">{{ $house->nickname }} &mdash; {{ $house->address_block }}</h4>
						</div>
						<div class="panel-body">
						@if($house->individuals_with_today_user_case_note->count() > 0)
							@foreach($house->individuals_with_today_user_case_note AS $individual)
								<fieldset>
								<h4 class="bg-primary"><a class="btn btn-sm btn-success" href="./individual/view/{{encrypt($individual->id)}}"><i class="fa fa-eye"></i></a> {{ $individual->first_name }} {{ $individual->last_name }}</h4>
								@if($individual->casenote_today_current_user == null)
									<div class="alert alert-warning">You have not entered a service note today.</div>
								@else
									<p>{{ $individual->casenote_today_current_user->case_note }}</p>
								@endif
							
								@if($individual->medications->count() > 0)
								<table class="table table-striped">
									<thead>
										<tr>
											<th>Medication</th>
											<th>Dosage</th>
											<th>Times/Take</th>
										</tr>
									</thead>
									<tbody>
										@foreach($individual->medications AS $medication)
											@if($medication->today_times->count() > 0)
											<tr>
												<td>{{ $medication->name }}</td>
												<td>{{ $medication->number_doses }} {{ $medication->type }} - {{ $medication->dosage }}</td>
												<td>
													@foreach($medication->today_times AS $time)
														{{ date('h:i A', strtotime($time->time)) }}
														
														@if(isset($time->missed))
															&mdash; Missed
														@elseif(isset($time->logged))
															&mdash; Taken {{ $time->logged->format('D h:i A') }}
														@elseif(strtotime($time->time) >= strtotime("-30 minutes") && strtotime($time->time) <= strtotime("+30 minutes"))
															&mdash; <a class="btn btn-sm btn-warning areYouSure" href="./individual/medication/{{encrypt($individual->id)}}/take/{{encrypt($medication->id)}}"><i class="fa fa-heart"></i></a>
														@endif
														<br />
													@endforeach
												</td>
											</tr>
											@elseif($medication->schedules->count() == 0)
											<tr>
												<td>{{ $medication->name }}</td>
												<td>{{ $medication->number_doses }} {{ $medication->type }} - {{ $medication->dosage }}</td>
												<td><a class="btn btn-sm btn-warning areYouSure" href="./individual/medication/{{encrypt($individual->id)}}/take/{{encrypt($medication->id)}}"><i class="fa fa-heart"></i></a></td>
											</tr>
											@endif
											
										@endforeach
									</tbody>
								</table>
								@endif
								<fieldset>
								<hr>
							@endforeach
						@else
							<h4 class="text-warning">No Individuals Assigned</h4>
						@endif
					</div>
				</div>
				@endforeach
							
			</div>
		</div>
	</div>
	<!-- end #content -->
@stop