routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', ['as' => 'login', 'uses' => 'Auth\LoginController@getLogin']);
Route::post('/login',           'Auth\LoginController@postLogin');
Route::any('/logout',           'Auth\LoginController@anyLogout');

Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::group(['middleware' => ['auth']], function()
{
	Route::get('/', 'DashboardController@getHome');
	Route::get('/my-profile', 'UserController@getProfile');
    Route::post('/my-profile/password', 'UserController@postProfilePassword');
});

Route::group(['middleware' => ['auth', 'group:provider']], function()
{
	Route::get('/individual/view/{id}', 'IndividualController@getViewIndividual');
	Route::get('/individual/casenote/{id}/add', 'IndividualController@getAddCaseNote');
	Route::post('/individual/casenote/{id}/add', 'IndividualController@postAddCaseNote');
	Route::get('/individual/casenote/{id}/edit/{cn_id}', 'IndividualController@getEditCaseNote');
	Route::post('/individual/casenote/{id}/edit/{cn_id}', 'IndividualController@postEditCaseNote');
	Route::get('/individual/medication/{id}/take/{med}', 'IndividualController@getTakeMedication');

	Route::get('/training/list','TrainingController@getTrainingList');
	Route::get('/training/take/{id}', 'TrainingController@getTrainingTake');
    Route::post('/training/take/{id}', 'TrainingController@postTrainingTake');
    
    Route::get('/clock/{punch}/{user_id?}', 'UserController@getClockInOut');

    Route::get('/house/schedule/{id}', 'HouseController@getHouseSchedule');
});

Route::group(['middleware' => ['auth', 'groupType:provider|Administrator;provider|Manager']], function()
{
	
	Route::get('/user/profile/{id}', 'UserController@getProfile');
	Route::get('/user/list', 'UserController@getUserList');
	Route::get('/user/add', 'UserController@getAddUser');
	Route::post('/user/add', 'UserController@postAddUser');
	Route::get('/user/edit/{id}', 'UserController@getEditUser');
    Route::post('/user/edit/{id}', 'UserController@postEditUser');
    Route::get('/user/remove/{id}', 'UserController@getRemoveUser');

    //user files
    Route::post('/user/file/{id}', 'UserController@postFileUser');
    Route::get('/user/file/{id}/remove/{ur_id}', 'UserController@getRemoveUserFileUpload');

	Route::get('/user/permission/{id}', 'UserController@getAddUserPermission');
	Route::post('/user/permission/{id}', 'UserController@postAddUserPermission');
	Route::get('/user/permission/{id}/remove/{ur_id}', 'UserController@getRemoveUserPermission');
	
	Route::post('/user/edit/{id}/house', 'UserController@postEditUserHouse');
	
	Route::get('/house/list', 'HouseController@getHouseList');
	Route::get('/house/add', 'HouseController@getAddHouse');
	Route::post('/house/add', 'HouseController@postAddHouse');
	Route::get('/house/edit/{id}', 'HouseController@getEditHouse');
	Route::post('/house/edit/{id}', 'HouseController@postEditHouse');
	Route::get('/house/view/{id}', 'HouseController@getViewHouse');
	Route::get('/house/safety-checklist/{id}/add', 'FormController@getSafetyChecklistAdd');
	Route::post('/house/safety-checklist/{id}/add', 'FormController@postSafetyChecklistAdd');
	Route::get('/house/safety-checklist/{id}/edit/{checklist_id}', 'FormController@getSafetyChecklistEdit');
	Route::post('/house/safety-checklist/{id}/edit/{checklist_id}', 'FormController@postSafetyChecklistAdd');
	Route::get('/house/safety-checklist/{id}/view/{checklist_id}', 'FormController@getSafetyChecklistView');	
	Route::get('/house/safety-checklist/{id}/remove/{checklist_id}', 'FormController@getSafetyChecklistRemove');	

    
	
	Route::get('/individual/list', 'IndividualController@getIndividualList');
	Route::get('/individual/add', 'IndividualController@getAddIndividual');
	Route::post('/individual/add', 'IndividualController@postAddIndividual');
	Route::get('/individual/edit/{id}', 'IndividualController@getEditIndividual');
	Route::post('/individual/edit/{id}', 'IndividualController@postEditIndividual');
	//edit/add house
	Route::post('/individual/edit/{id}/house', 'IndividualController@postEditIndividualHouse');
	
	Route::get('/individual/casenote/{id}/list', 'IndividualController@getListCaseNote');
	
	//medication for individual
	Route::get('/individual/medication/{id}/view', 'IndividualController@getViewMedication');
	Route::post('/individual/medication/{id}/add', 'IndividualController@postAddMedication');
	Route::get('/individual/medication/{id}/remove/{med}', 'IndividualController@getRemoveMedication');
	Route::get('/individual/medication/{id}/taken-report', 'IndividualController@getTakenMedication');
	Route::get('/individual/medication/{id}/remove/{med}/{med_taken_id}', 'IndividualController@getRemoveTakenMedication');
	
	//medical appointments
	Route::get('/individual/medical-appointment/{id}/add', 'IndividualController@getMedicalAppointmentAdd');
	Route::post('/individual/medical-appointment/{id}/add', 'IndividualController@postMedicalAppointmentAdd');
	Route::get('/individual/medical-appointment/{id}/edit/{apointment_id}', 'IndividualController@getMedicalAppointmentEdit');
	Route::post('/individual/medical-appointment/{id}/edit/{apointment_id}', 'IndividualController@postMedicalAppointmentAdd');
	Route::get('/individual/medical-appointment/{id}/view/{apointment_id}', 'IndividualController@getMedicalAppointmentView');
	Route::get('/individual/medical-appointment/{id}/remove/{apointment_id}', 'IndividualController@getMedicalAppointmentRemove');

	//support team
	Route::get('/individual/support-team/{id}/add', 'IndividualController@getSupportTeamAdd');
	Route::post('/individual/support-team/{id}/add', 'IndividualController@postSupportTeamAdd');
	Route::get('/individual/support-team/{id}/edit/{member_id}', 'IndividualController@getSupportTeamEdit');
	Route::post('/individual/support-team/{id}/edit/{member_id}', 'IndividualController@postSupportTeamAdd');
	Route::get('/individual/support-team/{id}/view/{member_id}', 'IndividualController@getSupportTeamView');
	Route::get('/individual/support-team/{id}/remove/{member_id}', 'IndividualController@getSupportTeamRemove');
	//suport team concerns
	Route::post('/individual/support-team/{id}/view/{member_id}', 'IndividualController@postSupportTeamConcernAdd');
	Route::get('/individual/team-concern/{id}/remove/{concern_id}', 'IndividualController@getSupportTeamConcernRemove');

	//seizure
	Route::get('/individual/seizures/{id}/add', 'IndividualController@getSeizuresAdd');
	Route::post('/individual/seizures/{id}/add', 'IndividualController@postSeizuresAdd');
	Route::get('/individual/seizures/{id}/edit/{seizure_id}', 'IndividualController@getSeizuresEdit');
	Route::post('/individual/seizures/{id}/edit/{seizure_id}', 'IndividualController@postSeizuresAdd');
	Route::get('/individual/seizures/{id}/view/{seizure_id}', 'IndividualController@getSeizuresView');
	Route::get('/individual/seizures/{id}/remove/{seizure_id}', 'IndividualController@getSeizuresRemove');

	//risk plans
	Route::get('/individual/risk-plan/{id}/add', 'IndividualController@getRiskPlanAdd');
	Route::post('/individual/risk-plan/{id}/add', 'IndividualController@postRiskPlanAdd');
	Route::get('/individual/risk-plan/{id}/edit/{seizure_id}', 'IndividualController@getRiskPlanEdit');
	Route::post('/individual/risk-plan/{id}/edit/{seizure_id}', 'IndividualController@postRiskPlanAdd');
	Route::get('/individual/risk-plan/{id}/remove/{seizure_id}', 'IndividualController@getRiskPlanRemove');

	//goals for individual
	Route::get('/individual/goal/{id}/view', 'IndividualController@getViewGoal');
	Route::post('/individual/goal/{id}/add', 'IndividualController@postAddGoal');
	Route::post('/individual/goal/{id}/strategy', 'IndividualController@postAddStrategy');
    Route::get('/individual/goal/{id}/remove/{goal_id}', 'IndividualController@getRemoveGoal');
    
    //note approval/reject
    Route::get('/individual/casenote/{id}/approve/{cn_id}', 'IndividualController@getCaseNoteApproval');    
    Route::get('/individual/casenote/{id}/reject/{cn_id}', 'IndividualController@getCaseNoteReject');
    Route::post('/individual/casenote/{id}/reject/{cn_id}', 'IndividualController@postCaseNoteReject');
    Route::get('/individual/casenote/{id}/unapprove/{cn_id}', 'IndividualController@getCaseNoteUnApprove');
	
	//Reports
	Route::get('/provider/report/case-notes/minor', 'ReportController@getMinorIncidentNote');
	Route::get('/provider/report/case-notes/major', 'ReportController@getMajorIncidentNote');
	Route::get('/provider/report/case-notes/by-individual', 'ReportController@getIndividualNote');
	Route::get('/provider/report/case-notes/with-qol', 'ReportController@getQolNote');
	Route::get('/provider/report/case-notes/approval', 'ReportController@getIndividualNoteApproval');
	Route::get('/provider/report/case-notes/approved', 'ReportController@getIndividualNoteApproved');
	Route::get('/provider/report/employee-list', 'ReportController@getEmployeeList');
	Route::get('/provider/report/medication/by-individual', 'ReportController@getMedicationByIndividual');
	Route::get('/provider/report/medication/missed-by-time', 'ReportController@getMissedMedicationByTime');
	Route::get('/provider/report/training/by-employee', 'ReportController@getTrainingByEmployee');

app/Models/ProviderIndividual.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Auth;

class ProviderIndividual extends Model
{
	use SoftDeletes;
	
	protected $table = 'tblProviderIndividual';
	
	protected $dates = ['created_at', 'updated_at', 'deleted_at', 'dob', 'dod'];
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */	
    protected $fillable = [
		'provider_id', 'first_name', 'last_name', 'ssn', 'dob', 'height', 'weight', 'email', 'phone', 'dod', 'about_me'
    ];

    protected $guarded = [];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
       
	];
	
	public function getFullNameAttribute()
	{
		return $this->first_name . ' ' . $this->last_name;
	}

	public function casenotes()
    {
        return $this->hasMany('App\Models\ProviderIndividualCaseNote', 'individual_id', 'id')->orderBy('note_date', 'DESC');
    }
	
	public function ten_casenotes()
    {
        return $this->hasMany('App\Models\ProviderIndividualCaseNote', 'individual_id', 'id')->orderBy('note_date', 'DESC')->limit(10);
    }
	
	public function casenote_today_current_user()
	{
		return $this->hasOne('App\Models\ProviderIndividualCaseNote', 'individual_id', 'id')->where('user_id', Auth::user()->id)->where('note_date', date('Y-m-d'))->orderBy('note_date', 'DESC')->limit(1);
	}
	
	public function report_casenotes()
	{
		return $this->hasMany('App\Models\ProviderIndividualCaseNote', 'individual_id', 'id')->with('user')->orderBy('note_date', 'DESC');
    }
	
	public function current_house()
    {
        return $this->belongsToMany('App\Models\ProviderHouse', 'tblProviderHouseIndividual', 'individual_id', 'house_id')->whereNull('tblProviderHouseIndividual.deleted_at');
	}
	
	public function field_checklists()
	{
		return $this->hasMany('App\Models\ProviderIndividualFormFieldChecklist', 'individual_id', 'id')->orderBy('date_complete', 'DESC');
	}

	public function quarterly_summaries()
	{
		return $this->hasMany('App\Models\ProviderIndividualFormQuarterlySummary', 'individual_id', 'id')->orderBy('date_complete', 'DESC');
	}
	
	public function houses()
    {
        return $this->belongsToMany('App\Models\ProviderHouse', 'tblProviderHouseIndividual', 'individual_id', 'house_id');
	}
	
	public function medical_appointments()
	{
		return $this->hasMany('App\Models\ProviderIndividualMedicalAppointment', 'individual_id', 'id');
	}
	
	public function medications()
	{
		return $this->hasMany('App\Models\ProviderIndividualMedication', 'individual_id', 'id');
	}
	
	public function goals()
	{
		return $this->hasMany('App\Models\ProviderIndividualGoal', 'individual_id', 'id');
    }
    
    public function strategies()
	{
		return $this->hasMany('App\Models\ProviderIndividualStrategy', 'individual_id', 'id');
	}

	public function seizures()
	{
		return $this->hasMany('App\Models\ProviderIndividualSeizure', 'individual_id', 'id');
	}
	
	public function risk_plans()
	{
		return $this->hasMany('App\Models\ProviderIndividualRiskPlan', 'individual_id', 'id');
	}

	public function support_team()
	{
		return $this->hasMany('App\Models\ProviderIndividualSupportTeam', 'individual_id', 'id');
	}
	
	public function retired_medications()
	{
		return $this->hasMany('App\Models\ProviderIndividualMedication', 'individual_id', 'id')->withTrashed()->whereNotNull('deleted_at');
	}
	
	public function medication_logs()
	{
		return $this->hasMany('App\Models\ProviderIndividualMedicationLog', 'individual_id', 'id');
    }
    
    public function graphs()
	{
		return $this->hasMany('App\Models\ProviderIndividualGraph', 'individual_id', 'id');
	}
	
	public function missed_meds($start_date=null, $end_date=null)
	{
		$this->missed = collect([]);
		$today = Carbon::now();
		if($start_date == null) {
			$start_date = Carbon::now();
		}
		if($end_date == null || $end_date > date('Y-m-d')) {
			$end_date = Carbon::now();
		}
		
		//loop over each day
		while($end_date >= $start_date) {
			
			//each medication
			foreach($this->medications AS $medication) {
				//each medication schedules
				foreach($medication->schedules AS $schedule) {
					//if the schedule lines up with the end_date
					
					if($schedule->day_of_week == date('N', strtotime($end_date))) {
						//check the log too see if it was taken on the day
						$logs = $medication->logs;
						$missed = true;

						foreach($logs AS $log) {
							$log->day_of_week--;
							if($log->day_of_week == 0) {
								$log->day_of_week = 7;
							}
							
							//3600 is one hour changed to 1800 for 30 minutes on each side
							if(date('YmdHis', strtotime($end_date->format('Y-m-d') . ' ' . $schedule->time) - 1800) <= date('YmdHis', strtotime($log->administered_dt)) && 
							   date('YmdHis', strtotime($log->administered_dt)) <= date('YmdHis', strtotime($end_date->format('Y-m-d') . ' ' . $schedule->time) + 1800)) {
								$missed = false;
								$schedule->logged = $log->administered_dt;
							}
						}
						if($missed == true && date('YmdHis', strtotime($today)) >= date('YmdHis', strtotime($end_date->format('Y-m-d') . ' ' . $schedule->time) + 1800)) {
							$this->missed->push(collect(['medication' => $medication, 'day' => date('m/d/Y', strtotime($end_date)), 'time' => date('h:i A', strtotime($schedule->time))]));// 'time' => $schedule->time);
						}
						
					}
				}
			}
			$end_date = $end_date->subDays(1); //subtract 1 day so we don't loop forever
		}
	}

	public function medications_with_missed($start_date=null, $end_date=null)
	{
		$this->missed = collect([]);
		$today = Carbon::now();
		if($start_date == null) {
			$start_date = Carbon::now();
		}
		if($end_date == null || $end_date > date('Y-m-d')) {
			$end_date = Carbon::now();
		}
		
		//loop over each day
		while($end_date >= $start_date) {
			
			//each medication
			foreach($this->medications AS $medication) {
				//each medication schedules
				foreach($medication->today_times AS $schedule) {
					//if the schedule lines up with the end_date
					
					if($schedule->day_of_week == date('N', strtotime($end_date))) {
						//check the log too see if it was taken on the day
						$logs = $medication->logs;
						$missed = true;

						foreach($logs AS $log) {
							$log->day_of_week--;
							if($log->day_of_week == 0) {
								$log->day_of_week = 7;
							}
							
							//3600 is one hour changed to 1800 for 30 minutes on each side
							if(date('YmdHis', strtotime($end_date->format('Y-m-d') . ' ' . $schedule->time) - 1800) <= date('YmdHis', strtotime($log->administered_dt)) && 
							   date('YmdHis', strtotime($log->administered_dt)) <= date('YmdHis', strtotime($end_date->format('Y-m-d') . ' ' . $schedule->time) + 1800)) {
								$schedule->logged = $log->administered_dt;
								$missed = false;
							}
						}
						if($missed == true && date('YmdHis', strtotime($today)) >= date('YmdHis', strtotime($end_date->format('Y-m-d') . ' ' . $schedule->time) + 1800)) {
							$schedule->missed = true;
						}
						
					}
				}
			}
			$end_date = $end_date->subDays(1); //subtract 1 day so we don't loop forever
		}
	}
}

resources/views/individual/risk-plan/add.blade.php
@extends('layouts.master.master')

@section('title', 'Risk Plan')


@section('content')
    <!-- begin #content -->
	<div id="content" class="content">
		<!-- begin breadcrumb -->
		<ol class="breadcrumb pull-right">
			<li><a href="/">Home</a></li>
			<li><a href="/individual/view/{{encrypt($individual->id)}}">{{$individual->full_name}}</a></li>
            <li>Risk Plan</li>
		</ol>
		<!-- end breadcrumb -->
		<!-- begin page-header -->
		<h1 class="page-header">{{$action}} Risk Plan for <a href="/individual/view/{{encrypt($individual->id)}}">{{$individual->full_name}}</a></h1>
		<!-- end page-header -->
				
		@include('includes.error.list')
		
		<div class="row">
			<div class="col-md-6">
				<!-- begin panel -->
				<div class="panel panel-success">
					<div class="panel-body">
						<form action="" method="POST">
							<input type="hidden" name="_token" value="{{ csrf_token() }}" />
							<fieldset>
								<div class="form-group">
									<label for="plan_date">Plan Date:</label>
									{!! Form::text('plan_date', isset($risk_plan->plan_date) ? $risk_plan->plan_date->format('m/d/Y') : null, ['class' => 'form-control calDatePicker', 'placeholder' => 'Enter Date']) !!}
								</div>
								<div class="form-group">
									<label for="plan_type">Last Name:</label>
									{!! Form::select('plan_type', $plan_types, $risk_plan->plan_type, ['class' => 'form-control', 'placeholder' => 'Please Select']) !!}
								</div>
							</fieldset>
							<button type="submit" class="btn btn-sm btn-primary m-r-5">{{$action}} Plan</button>
						</form>
					</div>
				</div>
				<!-- end panel -->
			</div>
			<!-- end col-6 -->		
		</div>
	</div>
	<!-- end #content -->
<script>
</script>
@stop

resources/views/individual/risk-plan/view.blade.php
@extends('layouts.master.master')

@section('title', 'Individual')


@section('content')
    <!-- begin #content -->
	<div id="content" class="content">
		<!-- begin breadcrumb -->
		<ol class="breadcrumb pull-right">
			<li>Goal/Strategy View</li>
		</ol>
		<!-- end breadcrumb -->
		<!-- begin page-header -->
		<h1 class="page-header">{{ $individual->first_name }} {{ $individual->last_name }}'s Goals</h1>
		<!-- end page-header -->
		
		@include('includes.error.list')
		
		<div class="row">
			<div class="col-md-12">
				<div class="panel panel-success">
					<div class="panel-heading">
						<h4 class="panel-title">Add Goal</h4>
					</div>
					<div class="panel-body">
						<div>
							<a class="btn btn-md btn-success" id="show_add_medication_form">{{ old('goal') !== null ? 'Cancel' : 'Add Goal' }}</a>
						</div>
						<div class="{{ old('goal') !== null ? '' : 'collapse' }}">
							<form method="POST" action="./add">
								<input type="hidden" name="_token" value="{{ csrf_token() }}"  />
								<fieldset>
									<legend>Add Goal</legend>
									<div class="form-group">
										<label for="goal">Goal</label>
										<textarea type="text" name="goal" class="form-control" placeholder="Enter Goal">{{ old('goal') }}</textarea>
									</div>
										
									<button type="submit" class="btn btn-md btn-primary m-r-5">Add Goal</button>
								</fieldset>
							</form>
						</div>
					</div>
				</div>
			</div>
			@if($individual->goals->count() == 0)
				<div class="col-md-12">
					<div class="panel panel-success">
						<div class="panel-heading">
							<h4 class="panel-title">Current Goals</h4>
						</div>
						<div class="panel-body">
							<div class="note note-warning"><h4>No Goals</h4></div>
						</div>
					</div>
				</div>
			@else
				@foreach($individual->goals AS $goal)
				<div class="col-md-12">
					<div class="panel panel-primary">
						<div class="panel-heading">
							<h4 class="panel-title">{{ $goal->goal }} <a href="/individual/goal/{{encrypt($individual->id)}}/remove/{{encrypt($goal->id)}}" class="btn btn-xs btn-danger pull-right areYouSure">Retire</a></h4> 
						</div>
						<div class="panel-body">
							
							@if($goal->strategies->count() > 0)
								<ol>
								@foreach($goal->strategies AS $k => $strategy)
									<li class="{{ $k % 2 == 0 ? 'bg-silver' : ''}}">{{ $strategy->strategy }}</li>
								@endforeach
								</ol>
							@else
								<div class="bg-warning">No Strategies</div>
							@endif
							<a class="btn btn-xs btn-primary strat_add_btn pull-right pull-bottom" id="{{encrypt($goal->id)}}">Add Strategy</a>							
						</div>
					</div>
				</div>
				@endforeach
			@endif
			<div class="col-md-12 collapse" id="strat_add_div">
				<div class="panel panel-success">
					<div class="panel-heading">
						<h4 class="panel-title">Add Strategy</h4>
					</div>
					<div class="panel-body">
						<form method="POST" action="./strategy">
							<input type="hidden" name="_token" value="{{ csrf_token() }}"  />
							<input type="hidden" name="goal_id" id="goal_id" value=""  />
							<fieldset>
								<div class="form-group">
									<label for="strategy">Strategy</label>
									<textarea type="text" id="strategy" name="strategy" class="form-control" placeholder="Enter Goal">{{ old('strategy') }}</textarea>
								</div>
									
								<button type="submit" class="btn btn-md btn-primary m-r-5">Add Strategy</button> <a id="strategy_cancel_form" class="btn btn-md btn-danger">Cancel</a>
							</fieldset>
						</form>
					</div>
				</div>
			</div>
			
		</div>
	</div>
	<!-- end #content -->
	<script>
		$('#show_add_medication_form').click(function () {
			
			if($(this).html() == 'Add Goal') {
				$(this).html('Cancel');
				$(this).addClass('btn-danger');
				$(this).removeClass('btn-success');
				$(this).parent().next().toggle('slow');
			}
			else {
				$(this).html('Add Goal');
				$(this).addClass('btn-success');
				$(this).removeClass('btn-danger');
				$(this).parent().next().toggle('slow');
			}
		});
		$('.strat_add_btn').click(function () {
			$(this).parent().parent().parent().parent().find('div.panel-body').removeClass('bg-warning');
			$(this).parent().addClass('bg-warning');
			$('#strat_add_div').show('slow');
			$('#goal_id').val($(this).attr('id'));
			$('#strategy').focus();
		});
		$('#strategy_cancel_form').click(function () {
			$('#strat_add_div').hide('slow');
			$(this).parent().parent().parent().parent().parent().parent().find('div.panel-body').removeClass('bg-warning');
			$('#goal_id').val('');
		});
	</script>
@stop