routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', ['as' => 'login', 'uses' => 'Auth\LoginController@getLogin']);
Route::post('/login',           'Auth\LoginController@postLogin');
Route::any('/logout',           'Auth\LoginController@anyLogout');

Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::group(['middleware' => ['auth']], function()
{
	Route::get('/', 'DashboardController@getHome');
	Route::get('/my-profile', 'UserController@getProfile');
    Route::post('/my-profile/password', 'UserController@postProfilePassword');
});

Route::group(['middleware' => ['auth', 'group:provider']], function()
{
	Route::get('/individual/view/{id}', 'IndividualController@getViewIndividual');
	Route::get('/individual/casenote/{id}/add', 'IndividualController@getAddCaseNote');
	Route::post('/individual/casenote/{id}/add', 'IndividualController@postAddCaseNote');
	Route::get('/individual/casenote/{id}/edit/{cn_id}', 'IndividualController@getEditCaseNote');
	Route::post('/individual/casenote/{id}/edit/{cn_id}', 'IndividualController@postEditCaseNote');
	Route::get('/individual/medication/{id}/take/{med}', 'IndividualController@getTakeMedication');

	Route::get('/training/list','TrainingController@getTrainingList');
	Route::get('/training/take/{id}', 'TrainingController@getTrainingTake');
    Route::post('/training/take/{id}', 'TrainingController@postTrainingTake');
    
    Route::get('/clock/{punch}/{user_id?}', 'UserController@getClockInOut');

    Route::get('/house/schedule/{id}', 'HouseController@getHouseSchedule');
});

Route::group(['middleware' => ['auth', 'groupType:provider|Administrator;provider|Manager']], function()
{
	
	Route::get('/user/profile/{id}', 'UserController@getProfile');
	Route::get('/user/list', 'UserController@getUserList');
	Route::get('/user/add', 'UserController@getAddUser');
	Route::post('/user/add', 'UserController@postAddUser');
	Route::get('/user/edit/{id}', 'UserController@getEditUser');
    Route::post('/user/edit/{id}', 'UserController@postEditUser');
    Route::get('/user/remove/{id}', 'UserController@getRemoveUser');

    //user files
    Route::post('/user/file/{id}', 'UserController@postFileUser');
    Route::get('/user/file/{id}/remove/{ur_id}', 'UserController@getRemoveUserFileUpload');

	Route::get('/user/permission/{id}', 'UserController@getAddUserPermission');
	Route::post('/user/permission/{id}', 'UserController@postAddUserPermission');
	Route::get('/user/permission/{id}/remove/{ur_id}', 'UserController@getRemoveUserPermission');
	
	Route::post('/user/edit/{id}/house', 'UserController@postEditUserHouse');
	
	Route::get('/house/list', 'HouseController@getHouseList');
	Route::get('/house/add', 'HouseController@getAddHouse');
	Route::post('/house/add', 'HouseController@postAddHouse');
	Route::get('/house/edit/{id}', 'HouseController@getEditHouse');
	Route::post('/house/edit/{id}', 'HouseController@postEditHouse');
	Route::get('/house/view/{id}', 'HouseController@getViewHouse');
	Route::get('/house/safety-checklist/{id}/add', 'FormController@getSafetyChecklistAdd');
	Route::post('/house/safety-checklist/{id}/add', 'FormController@postSafetyChecklistAdd');
	Route::get('/house/safety-checklist/{id}/edit/{checklist_id}', 'FormController@getSafetyChecklistEdit');
	Route::post('/house/safety-checklist/{id}/edit/{checklist_id}', 'FormController@postSafetyChecklistAdd');
	Route::get('/house/safety-checklist/{id}/view/{checklist_id}', 'FormController@getSafetyChecklistView');	
	Route::get('/house/safety-checklist/{id}/remove/{checklist_id}', 'FormController@getSafetyChecklistRemove');	

    
	
	Route::get('/individual/list', 'IndividualController@getIndividualList');
	Route::get('/individual/add', 'IndividualController@getAddIndividual');
	Route::post('/individual/add', 'IndividualController@postAddIndividual');
	Route::get('/individual/edit/{id}', 'IndividualController@getEditIndividual');
	Route::post('/individual/edit/{id}', 'IndividualController@postEditIndividual');
	//edit/add house
	Route::post('/individual/edit/{id}/house', 'IndividualController@postEditIndividualHouse');
	
	Route::get('/individual/casenote/{id}/list', 'IndividualController@getListCaseNote');
	
	//medication for individual
	Route::get('/individual/medication/{id}/view', 'IndividualController@getViewMedication');
	Route::post('/individual/medication/{id}/add', 'IndividualController@postAddMedication');
	Route::get('/individual/medication/{id}/remove/{med}', 'IndividualController@getRemoveMedication');
	Route::get('/individual/medication/{id}/taken-report', 'IndividualController@getTakenMedication');
	Route::get('/individual/medication/{id}/remove/{med}/{med_taken_id}', 'IndividualController@getRemoveTakenMedication');
	
	//medical appointments
	Route::get('/individual/medical-appointment/{id}/add', 'IndividualController@getMedicalAppointmentAdd');
	Route::post('/individual/medical-appointment/{id}/add', 'IndividualController@postMedicalAppointmentAdd');
	Route::get('/individual/medical-appointment/{id}/edit/{apointment_id}', 'IndividualController@getMedicalAppointmentEdit');
	Route::post('/individual/medical-appointment/{id}/edit/{apointment_id}', 'IndividualController@postMedicalAppointmentAdd');
	Route::get('/individual/medical-appointment/{id}/view/{apointment_id}', 'IndividualController@getMedicalAppointmentView');
	Route::get('/individual/medical-appointment/{id}/remove/{apointment_id}', 'IndividualController@getMedicalAppointmentRemove');

	//support team
	Route::get('/individual/support-team/{id}/add', 'IndividualController@getSupportTeamAdd');
	Route::post('/individual/support-team/{id}/add', 'IndividualController@postSupportTeamAdd');
	Route::get('/individual/support-team/{id}/edit/{member_id}', 'IndividualController@getSupportTeamEdit');
	Route::post('/individual/support-team/{id}/edit/{member_id}', 'IndividualController@postSupportTeamAdd');
	Route::get('/individual/support-team/{id}/view/{member_id}', 'IndividualController@getSupportTeamView');
	Route::get('/individual/support-team/{id}/remove/{member_id}', 'IndividualController@getSupportTeamRemove');
	//suport team concerns
	Route::post('/individual/support-team/{id}/view/{member_id}', 'IndividualController@postSupportTeamConcernAdd');
	Route::get('/individual/team-concern/{id}/remove/{concern_id}', 'IndividualController@getSupportTeamConcernRemove');

	//seizure
	Route::get('/individual/seizures/{id}/add', 'IndividualController@getSeizuresAdd');
	Route::post('/individual/seizures/{id}/add', 'IndividualController@postSeizuresAdd');
	Route::get('/individual/seizures/{id}/edit/{seizure_id}', 'IndividualController@getSeizuresEdit');
	Route::post('/individual/seizures/{id}/edit/{seizure_id}', 'IndividualController@postSeizuresAdd');
	Route::get('/individual/seizures/{id}/view/{seizure_id}', 'IndividualController@getSeizuresView');
	Route::get('/individual/seizures/{id}/remove/{seizure_id}', 'IndividualController@getSeizuresRemove');

	//risk plans
	Route::get('/individual/risk-plan/{id}/add', 'IndividualController@getRiskPlanAdd');
	Route::post('/individual/risk-plan/{id}/add', 'IndividualController@postRiskPlanAdd');
	Route::get('/individual/risk-plan/{id}/edit/{seizure_id}', 'IndividualController@getRiskPlanEdit');
	Route::post('/individual/risk-plan/{id}/edit/{seizure_id}', 'IndividualController@postRiskPlanAdd');
	Route::get('/individual/risk-plan/{id}/remove/{seizure_id}', 'IndividualController@getRiskPlanRemove');

	//goals for individual
	Route::get('/individual/goal/{id}/view', 'IndividualController@getViewGoal');
	Route::post('/individual/goal/{id}/add', 'IndividualController@postAddGoal');
	Route::post('/individual/goal/{id}/strategy', 'IndividualController@postAddStrategy');
    Route::get('/individual/goal/{id}/remove/{goal_id}', 'IndividualController@getRemoveGoal');
    
    //note approval/reject
    Route::get('/individual/casenote/{id}/approve/{cn_id}', 'IndividualController@getCaseNoteApproval');    
    Route::get('/individual/casenote/{id}/reject/{cn_id}', 'IndividualController@getCaseNoteReject');
    Route::post('/individual/casenote/{id}/reject/{cn_id}', 'IndividualController@postCaseNoteReject');
    Route::get('/individual/casenote/{id}/unapprove/{cn_id}', 'IndividualController@getCaseNoteUnApprove');
	
	//Reports
	Route::get('/provider/report/case-notes/minor', 'ReportController@getMinorIncidentNote');
	Route::get('/provider/report/case-notes/major', 'ReportController@getMajorIncidentNote');
	Route::get('/provider/report/case-notes/by-individual', 'ReportController@getIndividualNote');
	Route::get('/provider/report/case-notes/with-qol', 'ReportController@getQolNote');
	Route::get('/provider/report/case-notes/approval', 'ReportController@getIndividualNoteApproval');
	Route::get('/provider/report/case-notes/approved', 'ReportController@getIndividualNoteApproved');
	Route::get('/provider/report/employee-list', 'ReportController@getEmployeeList');
	Route::get('/provider/report/medication/by-individual', 'ReportController@getMedicationByIndividual');
	Route::get('/provider/report/medication/missed-by-time', 'ReportController@getMissedMedicationByTime');
	Route::get('/provider/report/training/by-employee', 'ReportController@getTrainingByEmployee');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Authenticatable
{
    use Notifiable;
	use SoftDeletes;
	
	protected $table = 'tblUser';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */	
    protected $guarded = [];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
	
	public function roles()
    {
        return $this->belongsToMany('App\Models\Role', 'tblUserRole', 'user_id', 'role_id')->withPivot('id', 'created_at', 'deleted_at')->whereNull('tblUserRole.deleted_at');
    }
	
	public function hasGroup($name)
    {
        if(is_array($name)) {
            foreach($name as $roleName) {
                $hasRole = $this->hasGroup($roleName);
				if($hasRole) return true;
			}
            
        } else {
			//dd($this);
            foreach ($this->roles as $role) {
				//dd($role);
                if ($role->group == $name && NULL === $role->pivot->deleted_at) {
                    return true;
                }
            }
        }
        
        return false;
    }
	
	public function hasGroupType($group, $type)
    {       
		if(is_array($type)) {
            foreach($type as $roleType) {
                $hasType = $this->hasGroupType($group, $roleType);
				if($hasType) return true;
			}
            
        } else {
			foreach ($this->roles as $role) {
				if($role->group == $group && $role->type == $type && NULL === $role->pivot->deleted_at) {
					return true;
				}
			}
		}

        
        return false;
    }
	
	public function provider()
    {
        return $this->hasOne('App\Models\Provider', 'id', 'provider_id');
    }
	
	public function current_houses()
    {
        return $this->belongsToMany('App\Models\ProviderHouse', 'tblProviderHouseUser', 'user_id', 'house_id')->whereNull('tblProviderHouseUser.deleted_at');
    }
	
	public function houses()
    {
        return $this->belongsToMany('App\Models\ProviderHouse', 'tblProviderHouseUser', 'user_id', 'house_id');
    }
    
    public function trainings()
    {
        return $this->belongsToMany('App\Models\ProviderTraining', 'tblProviderTrainingUser', 'user_id', 'training_id')
                        ->withPivot('score', 'created_at')
                        ->whereNull('tblProviderTrainingUser.deleted_at');
    }

    public function files()
    {
        return $this->belongsToMany('App\Models\FileUpload', 'tblFileUploadUser', 'user_id', 'file_upload_id')
                    ->withPivot('start_date', 'end_date', 'file_type')
                    ->whereNull('tblFileUploadUser.deleted_at');
    }

    public function time_punches()
    {
        return $this->hasMany('App\Models\UserTimePunch', 'user_id', 'id')->orderBy('time_punch', 'DESC');
    }

    public function getClockedInOutAttribute()
    {
        return $this->time_punches->first();
    }

    public function calculate_hours()
    {
        $this->punched_hours = collect([]);
        if($this->time_punches->count() > 0) {
            $check_punch = false;
            foreach($this->time_punches AS $punch) {
                
                if($punch->punch == 'out') {
                    $check_punch = true;
                    $single_punch = collect([]);
                    $single_punch->put('punch_out', $punch->time_punch);
                }
                if($punch->punch == 'in' && $check_punch == true) {
                    $check_punch = false;
                    $single_punch->put('punch_in', $punch->time_punch);
                    $single_punch->put('hours', $single_punch['punch_out']->diff($punch->time_punch)->format('%H:%I'));
                    $this->punched_hours->push($single_punch);
                }
            }
        }
    }
}

resources/views/layouts/master/includes/footer.blade.php
<!-- ================== BEGIN BASE JS ================== -->	
	<script src="/assets/plugins/jquery/jquery-1.9.1.js"></script>
	<script src="/assets/plugins/jquery-ui/ui/minified/jquery-ui.min.js"></script>
	<script src="/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
	<!--[if lt IE 9]>
		<script src="/assets/crossbrowserjs/html5shiv.js"></script>
		<script src="/assets/crossbrowserjs/respond.min.js"></script>
		<script src="/assets/crossbrowserjs/excanvas.min.js"></script>
	<![endif]-->
	<script src="/assets/plugins/slimscroll/jquery.slimscroll.min.js"></script>
	<script src="/assets/plugins/jquery-cookie/jquery.cookie.js"></script>
	<!-- ================== END BASE JS ================== -->
	
	<!-- ================== BEGIN PAGE LEVEL JS ================== -->
	<script src="/assets/plugins/isotope/jquery.isotope.min.js"></script>
  	<script src="/assets/plugins/lightbox/js/lightbox-2.6.min.js"></script>
	<script src="/assets/plugins/superbox/js/superbox.js"></script>	
	
	<script src="/assets/plugins/DataTables/media/js/jquery.dataTables.js"></script>
	<script src="/assets/plugins/DataTables/media/js/dataTables.bootstrap.min.js"></script>
	<script src="/assets/plugins/DataTables/extensions/Responsive/js/dataTables.responsive.min.js"></script>
	<script src="/assets/plugins/bootstrap-timepicker/js/bootstrap-timepicker.min.js"></script>
		
	<script src="/assets/plugins/DataTables/extensions/Buttons/js/dataTables.buttons.min.js"></script>
	<script src="/assets/plugins/DataTables/extensions/Buttons/js/buttons.bootstrap.min.js"></script>
	<script src="/assets/plugins/DataTables/extensions/Buttons/js/buttons.print.min.js"></script>
	<script src="/assets/plugins/DataTables/extensions/Buttons/js/buttons.flash.min.js"></script>
	<script src="/assets/plugins/DataTables/extensions/Buttons/js/buttons.html5.min.js"></script>
	<script src="/assets/plugins/DataTables/extensions/Buttons/js/buttons.colVis.min.js"></script>
	
	<script src="/assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
	<script src="/assets/plugins/ionRangeSlider/js/ion-rangeSlider/ion.rangeSlider.min.js"></script>
	<script src="/assets/plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.min.js"></script>
	<script src="/assets/plugins/masked-input/masked-input.min.js"></script>
	<script src="/assets/plugins/bootstrap-timepicker/js/bootstrap-timepicker.min.js"></script>
	<script src="/assets/plugins/password-indicator/js/password-indicator.js"></script>
	<script src="/assets/plugins/bootstrap-combobox/js/bootstrap-combobox.js"></script>
	<script src="/assets/plugins/bootstrap-select/bootstrap-select.min.js"></script>
	<script src="/assets/plugins/bootstrap-tagsinput/bootstrap-tagsinput.min.js"></script>
	<script src="/assets/plugins/bootstrap-tagsinput/bootstrap-tagsinput-typeahead.js"></script>
	<script src="/assets/plugins/jquery-tag-it/js/tag-it.min.js"></script>
    <script src="/assets/plugins/bootstrap-daterangepicker/moment.js"></script>
    <script src="/assets/plugins/bootstrap-daterangepicker/daterangepicker.js"></script>
    <script src="/assets/plugins/select2/dist/js/select2.min.js"></script>
    <script src="/assets/plugins/bootstrap-eonasdan-datetimepicker/build/js/bootstrap-datetimepicker.min.js"></script>
	<script src="/assets/js/apps.min.js"></script>
	
	
	<!-- ================== END PAGE LEVEL JS ================== -->
	<div class="modal fade" id="are-you-sure">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
					<h4 class="modal-title">Alert</h4>
				</div>
				<div class="modal-body">
					<div class="alert alert-danger m-b-0">
						<h4><i class="fa fa-info-circle"></i> Are you sure?</h4>
						<p></p>
					</div>
				</div>
				<div class="modal-footer text-center">
					<a href="javascript:;" class="btn btn-sm btn-danger" id="i_am_sure">Yes</a>
					<a href="javascript:;" class="btn btn-sm btn-info" data-dismiss="modal">No</a>
				</div>
			</div>
		</div>
	</div>

	<script>
		$(document).ready(function() {
            App.init();
            //TableManageDefault.init();
            $('.calDatePickerOpen').datepicker({
				todayHighlight: true,
				autoclose: true
			});
			$('.calDatePicker').datepicker({
				todayHighlight: true,
				autoclose: true,
				endDate: new Date(new Date().setDate(new Date().getDate()))
			});
			$('.calDateTimePicker').datetimepicker({
				maxDate: Date(),
				sideBySide: true
			});
			$('.timePicker').datetimepicker({
				format: 'LT'
			});
			$('.table-manage').each(function () {
				if($(this).length !== 0) {
					$(this).dataTable().fnDestroy();
					$(this).dataTable({
						dom: 'Bfrtip',
						buttons: [
							{ extend: 'csv', className: 'btn-sm' },
							{ extend: 'pdf', className: 'btn-sm' },
						],
						responsive: true
					});
				}
			});
			$(".multiple-select").select2({});
			var modal_href = '';
			$('.areYouSure').click(function(e) {
				e.preventDefault();
				$('#are-you-sure').modal();
				modal_href = $(this).attr('href');
			});
			$('#i_am_sure').click(function () {
				$('#are-you-sure').modal('hide');
				window.location = modal_href;
				modal_href = '';
			});
		});
	</script>

resources/views/layouts/master/includes/header.blade.php
	<!-- begin #header -->
	<div id="header" class="header navbar navbar-default navbar-fixed-top navbar-inverse">
		<!-- begin container-fluid -->
		<div class="container-fluid">
			<!-- begin mobile sidebar expand / collapse button -->
			<div class="navbar-header">
				<a href="/" class="navbar-brand"><span class="navbar-logo"></span> DocuMentor</a>
				<button type="button" class="navbar-toggle" data-click="sidebar-toggled">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
			</div>
			<!-- end mobile sidebar expand / collapse button -->
			
			
			
			<!-- begin header navigation right -->
			<ul class="nav navbar-nav navbar-right">
				
				<li class="dropdown navbar-user">
					<a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
						<span class="hidden-xs">{{ Auth::user()->first_name }} {{ Auth::user()->last_name }}</span> <b class="caret"></b>
					</a>
					<ul class="dropdown-menu animated fadeInLeft">
						<li class="arrow"></li>
						<li><a href="/my-profile">Setting</a></li>
						<li class="divider"></li>
						<li><a href="/logout">Log Out</a></li>
					</ul>
				</li>
			</ul>
			<!-- end header navigation right -->
		</div>
		<!-- end container-fluid -->
	</div>
	<!-- end #header -->

resources/views/layouts/master/includes/sidebar.blade.php
<!-- begin #sidebar -->
<div id="sidebar" class="sidebar">
	<!-- begin sidebar scrollbar -->
	<div data-scrollbar="true" data-height="100%">
		<!-- begin sidebar nav -->
		<ul class="nav">
			<li class="nav-header"></li>
			<li>
				<a href="/">
					<i class="fa fa-dashboard"></i> 
					<span>Dashboard</span>
				</a>
			</li>
			@if(Auth::user()->hasGroupType('provider','Administrator'))
			<li class="has-sub">
				<a href="javascript:;">
					<b class="caret pull-right"></b>
					<i class="fa fa-users"></i> 
					<span>User Tools</span>
				</a>
				<ul class="sub-menu">
					<li><a href="/user/list">User List</a></li>
					<li><a href="/user/add">Add User</a></li>					
				</ul>
			</li>
			
			<li class="has-sub">
				
				<a href="javascript:;">
					<b class="caret pull-right"></b>
					<i class="fa fa-home"></i> 
					<span>House Tools</span>
				</a>
				<ul class="sub-menu">
					<li><a href="/house/list">House List</a></li>
						<li><a href="/house/add">Add House</a></li>
				</ul>
			</li>
			<li class="has-sub">
				<a href="javascript:;">
					<b class="caret pull-right"></b>
					<i class="fa fa-child"></i> 
					<span>Individual Tools</span>
				</a>
				<ul class="sub-menu">
					<li><a href="/individual/list">Individual List</a></li>
					<li><a href="/individual/add">Add Individual</a></li>
				</ul>
			</li>
			<li class="has-sub">
				<a href="javascript:;">
					<b class="caret pull-right"></b>
					<i class="fa fa-bar-chart"></i> 
					<span>Reports</span>
				</a>
				<ul class="sub-menu">
					<li class="has-sub">
						<a href="javascript:;">
							<b class="caret pull-right"></b>
							<span>Case Note/Incident</span>
						</a>
						<ul class="sub-menu">
							<li><a href="/provider/report/case-notes/approval">Approve Case Note</a></li>
							<li><a href="/provider/report/case-notes/approved">Approved Case Note</a></li>
							<li><a href="/provider/report/case-notes/by-individual">Service Notes By Individual</a></li>
							<li><a href="/provider/report/case-notes/with-qol">Service Notes w/ QoL Data</a></li>
							<li><a href="/provider/report/case-notes/minor">Non Reportable Incident Notes</a></li>
							<li><a href="/provider/report/case-notes/major">Reportable Incident Notes</a></li>
						</ul>
					</li>
					<li class="has-sub">
						<a href="javascript:;">
							<b class="caret pull-right"></b>
							<span>Medication</span>
						</a>
						<ul class="sub-menu">
							<li><a href="/provider/report/medication/missed-by-time">Missed by Time</a></li>
							<li><a href="/provider/report/medication/by-individual">By Individual</a></li>
						</ul>
					</li>
					<li class="has-sub">
						<a href="javascript:;">
							<b class="caret pull-right"></b>
							<span>Training</span>
						</a>
						<ul class="sub-menu">
							<li><a href="/provider/report/training/by-employee">Training By Employee</a></li>
						</ul>
					</li>
                    <li class="has-sub">
						<a href="javascript:;">
							<b class="caret pull-right"></b>
							<span>Time Punches</span>
						</a>
						<ul class="sub-menu">
							<li><a href="/provider/report/time-punches/by-employee">Punches By Employee</a></li>
							<li><a href="/provider/report/time-punches/employee-hours">Hours By Employee</a></li>
						</ul>
					</li>
				</ul>
			</li>
			@endif
			<li class="has-sub">
				<a href="javascript:;">
					<b class="caret pull-right"></b>
					<i class="fa fa-book"></i> 
					<span>Training Tools</span>
				</a>
				<ul class="sub-menu">
					<li><a href="/training/list">Training List</a></li>
					@if(Auth::user()->hasGroupType('provider','Administrator'))
					<li><a href="/training/add">Add Training</a></li>				
					@endif	
				</ul>
			</li>
			@if(Auth::user()->hasGroupType('site','admin'))
			<li class="has-sub">
				<a href="javascript:;">
					<b class="caret pull-right"></b>
					<i class="fa fa-university"></i> 
					<span>Admin Tools</span>
				</a>
				<ul class="sub-menu">
					<li><a href="/site-admin/provider/list">Provider List</a></li>
				</ul>
			</li>
			@endif
            <div class="text-center p-t-10">
                @if(!Auth::user()->clocked_in_out || (Auth::user()->clocked_in_out && Auth::user()->clocked_in_out->punch == 'out'))
                    <a class="btn btn-sm btn-primary areYouSure clockInOut" href="/clock/in"><i class="fa fa-clock-o"></i> Clock In</a>
                @else
                    <a class="btn btn-sm btn-warning areYouSure clockInOut" href="/clock/out"><i class="fa fa-clock-o"></i> Clock Out</a>
                @endif
            </div>
			<!-- begin sidebar minify button -->
			<li><a href="javascript:;" class="sidebar-minify-btn" data-click="sidebar-minify"><i class="fa fa-angle-double-left"></i></a></li>
			<!-- end sidebar minify button -->
		</ul>
		<!-- end sidebar nav -->
	</div>
	<!-- end sidebar scrollbar -->
</div>
<div class="sidebar-bg"></div>
<!-- end #sidebar -->