routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', ['as' => 'login', 'uses' => 'Auth\LoginController@getLogin']);
Route::post('/login',           'Auth\LoginController@postLogin');
Route::any('/logout',           'Auth\LoginController@anyLogout');

Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::group(['middleware' => ['auth']], function()
{
	Route::get('/', 'DashboardController@getHome');
	Route::get('/my-profile', 'UserController@getProfile');
    Route::post('/my-profile/password', 'UserController@postProfilePassword');
});

Route::group(['middleware' => ['auth', 'group:provider']], function()
{
	Route::get('/individual/view/{id}', 'IndividualController@getViewIndividual');
	Route::get('/individual/casenote/{id}/add', 'IndividualController@getAddCaseNote');
	Route::post('/individual/casenote/{id}/add', 'IndividualController@postAddCaseNote');
	Route::get('/individual/casenote/{id}/edit/{cn_id}', 'IndividualController@getEditCaseNote');
	Route::post('/individual/casenote/{id}/edit/{cn_id}', 'IndividualController@postEditCaseNote');
	Route::get('/individual/medication/{id}/take/{med}', 'IndividualController@getTakeMedication');

	Route::get('/training/list','TrainingController@getTrainingList');
	Route::get('/training/take/{id}', 'TrainingController@getTrainingTake');
    Route::post('/training/take/{id}', 'TrainingController@postTrainingTake');
    
    Route::get('/clock/{punch}/{user_id?}', 'UserController@getClockInOut');

    Route::get('/house/schedule/{id}', 'HouseController@getHouseSchedule');
});

Route::group(['middleware' => ['auth', 'groupType:provider|Administrator;provider|Manager']], function()
{
	
	Route::get('/user/profile/{id}', 'UserController@getProfile');
	Route::get('/user/list', 'UserController@getUserList');
	Route::get('/user/add', 'UserController@getAddUser');
	Route::post('/user/add', 'UserController@postAddUser');
	Route::get('/user/edit/{id}', 'UserController@getEditUser');
    Route::post('/user/edit/{id}', 'UserController@postEditUser');
    Route::get('/user/remove/{id}', 'UserController@getRemoveUser');

    //user files
    Route::post('/user/file/{id}', 'UserController@postFileUser');
    Route::get('/user/file/{id}/remove/{ur_id}', 'UserController@getRemoveUserFileUpload');

	Route::get('/user/permission/{id}', 'UserController@getAddUserPermission');
	Route::post('/user/permission/{id}', 'UserController@postAddUserPermission');
	Route::get('/user/permission/{id}/remove/{ur_id}', 'UserController@getRemoveUserPermission');
	
	Route::post('/user/edit/{id}/house', 'UserController@postEditUserHouse');
	
	Route::get('/house/list', 'HouseController@getHouseList');
	Route::get('/house/add', 'HouseController@getAddHouse');
	Route::post('/house/add', 'HouseController@postAddHouse');
	Route::get('/house/edit/{id}', 'HouseController@getEditHouse');
	Route::post('/house/edit/{id}', 'HouseController@postEditHouse');
	Route::get('/house/view/{id}', 'HouseController@getViewHouse');
	Route::get('/house/safety-checklist/{id}/add', 'FormController@getSafetyChecklistAdd');
	Route::post('/house/safety-checklist/{id}/add', 'FormController@postSafetyChecklistAdd');
	Route::get('/house/safety-checklist/{id}/edit/{checklist_id}', 'FormController@getSafetyChecklistEdit');
	Route::post('/house/safety-checklist/{id}/edit/{checklist_id}', 'FormController@postSafetyChecklistAdd');
	Route::get('/house/safety-checklist/{id}/view/{checklist_id}', 'FormController@getSafetyChecklistView');	
	Route::get('/house/safety-checklist/{id}/remove/{checklist_id}', 'FormController@getSafetyChecklistRemove');	

    
	
	Route::get('/individual/list', 'IndividualController@getIndividualList');
	Route::get('/individual/add', 'IndividualController@getAddIndividual');
	Route::post('/individual/add', 'IndividualController@postAddIndividual');
	Route::get('/individual/edit/{id}', 'IndividualController@getEditIndividual');
	Route::post('/individual/edit/{id}', 'IndividualController@postEditIndividual');
	//edit/add house
	Route::post('/individual/edit/{id}/house', 'IndividualController@postEditIndividualHouse');
	
	Route::get('/individual/casenote/{id}/list', 'IndividualController@getListCaseNote');
	
	//medication for individual
	Route::get('/individual/medication/{id}/view', 'IndividualController@getViewMedication');
	Route::post('/individual/medication/{id}/add', 'IndividualController@postAddMedication');
	Route::get('/individual/medication/{id}/remove/{med}', 'IndividualController@getRemoveMedication');
	Route::get('/individual/medication/{id}/taken-report', 'IndividualController@getTakenMedication');
	Route::get('/individual/medication/{id}/remove/{med}/{med_taken_id}', 'IndividualController@getRemoveTakenMedication');
	
	//medical appointments
	Route::get('/individual/medical-appointment/{id}/add', 'IndividualController@getMedicalAppointmentAdd');
	Route::post('/individual/medical-appointment/{id}/add', 'IndividualController@postMedicalAppointmentAdd');
	Route::get('/individual/medical-appointment/{id}/edit/{apointment_id}', 'IndividualController@getMedicalAppointmentEdit');
	Route::post('/individual/medical-appointment/{id}/edit/{apointment_id}', 'IndividualController@postMedicalAppointmentAdd');
	Route::get('/individual/medical-appointment/{id}/view/{apointment_id}', 'IndividualController@getMedicalAppointmentView');
	Route::get('/individual/medical-appointment/{id}/remove/{apointment_id}', 'IndividualController@getMedicalAppointmentRemove');

	//support team
	Route::get('/individual/support-team/{id}/add', 'IndividualController@getSupportTeamAdd');
	Route::post('/individual/support-team/{id}/add', 'IndividualController@postSupportTeamAdd');
	Route::get('/individual/support-team/{id}/edit/{member_id}', 'IndividualController@getSupportTeamEdit');
	Route::post('/individual/support-team/{id}/edit/{member_id}', 'IndividualController@postSupportTeamAdd');
	Route::get('/individual/support-team/{id}/view/{member_id}', 'IndividualController@getSupportTeamView');
	Route::get('/individual/support-team/{id}/remove/{member_id}', 'IndividualController@getSupportTeamRemove');
	//suport team concerns
	Route::post('/individual/support-team/{id}/view/{member_id}', 'IndividualController@postSupportTeamConcernAdd');
	Route::get('/individual/team-concern/{id}/remove/{concern_id}', 'IndividualController@getSupportTeamConcernRemove');

	//seizure
	Route::get('/individual/seizures/{id}/add', 'IndividualController@getSeizuresAdd');
	Route::post('/individual/seizures/{id}/add', 'IndividualController@postSeizuresAdd');
	Route::get('/individual/seizures/{id}/edit/{seizure_id}', 'IndividualController@getSeizuresEdit');
	Route::post('/individual/seizures/{id}/edit/{seizure_id}', 'IndividualController@postSeizuresAdd');
	Route::get('/individual/seizures/{id}/view/{seizure_id}', 'IndividualController@getSeizuresView');
	Route::get('/individual/seizures/{id}/remove/{seizure_id}', 'IndividualController@getSeizuresRemove');

	//risk plans
	Route::get('/individual/risk-plan/{id}/add', 'IndividualController@getRiskPlanAdd');
	Route::post('/individual/risk-plan/{id}/add', 'IndividualController@postRiskPlanAdd');
	Route::get('/individual/risk-plan/{id}/edit/{seizure_id}', 'IndividualController@getRiskPlanEdit');
	Route::post('/individual/risk-plan/{id}/edit/{seizure_id}', 'IndividualController@postRiskPlanAdd');
	Route::get('/individual/risk-plan/{id}/remove/{seizure_id}', 'IndividualController@getRiskPlanRemove');

	//goals for individual
	Route::get('/individual/goal/{id}/view', 'IndividualController@getViewGoal');
	Route::post('/individual/goal/{id}/add', 'IndividualController@postAddGoal');
	Route::post('/individual/goal/{id}/strategy', 'IndividualController@postAddStrategy');
    Route::get('/individual/goal/{id}/remove/{goal_id}', 'IndividualController@getRemoveGoal');
    
    //note approval/reject
    Route::get('/individual/casenote/{id}/approve/{cn_id}', 'IndividualController@getCaseNoteApproval');    
    Route::get('/individual/casenote/{id}/reject/{cn_id}', 'IndividualController@getCaseNoteReject');
    Route::post('/individual/casenote/{id}/reject/{cn_id}', 'IndividualController@postCaseNoteReject');
    Route::get('/individual/casenote/{id}/unapprove/{cn_id}', 'IndividualController@getCaseNoteUnApprove');
	
	//Reports
	Route::get('/provider/report/case-notes/minor', 'ReportController@getMinorIncidentNote');
	Route::get('/provider/report/case-notes/major', 'ReportController@getMajorIncidentNote');
	Route::get('/provider/report/case-notes/by-individual', 'ReportController@getIndividualNote');
	Route::get('/provider/report/case-notes/with-qol', 'ReportController@getQolNote');
	Route::get('/provider/report/case-notes/approval', 'ReportController@getIndividualNoteApproval');
	Route::get('/provider/report/case-notes/approved', 'ReportController@getIndividualNoteApproved');
	Route::get('/provider/report/employee-list', 'ReportController@getEmployeeList');
	Route::get('/provider/report/medication/by-individual', 'ReportController@getMedicationByIndividual');
	Route::get('/provider/report/medication/missed-by-time', 'ReportController@getMissedMedicationByTime');
	Route::get('/provider/report/training/by-employee', 'ReportController@getTrainingByEmployee');

app/Models/ProviderTraining.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class ProviderTraining extends Model
{
	use SoftDeletes;
	
	protected $table = 'tblProviderTraining';
	
	protected $dates = ['created_at', 'updated_at', 'deleted_at'];
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */	
    protected $guarded = [];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
       
    ];
    
    public function individual()
    {
        return $this->hasOne('App\Models\ProviderIndividual', 'id', 'individual_id');
    }

    public function questions()
    {
        return $this->hasMany('App\Models\ProviderTrainingQuestion', 'training_id', 'id');
    }

    public function getTitleNameAttribute()
    {
        return $this->individual_id ? $this->individual->first_name . ' ' . $this->individual->last_name : $this->title;
    }
}

app/Http/Controllers/TrainingController.php
<?php

namespace App\Http\Controllers;

use Auth;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Classes\Upload;
use App\Models\User;
use App\Models\Role;
use App\Models\UserRole;
use App\Models\FileUpload;
use App\Models\ProviderIndividual;
use App\Models\ProviderHouse;
use App\Models\ProviderHouseUser;
use App\Models\ProviderTraining;
use App\Models\ProviderTrainingUser;
use App\Models\ProviderTrainingQuestion;
use App\Models\ProviderTrainingQuestionAnswer;

class TrainingController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | Training Controller
    |--------------------------------------------------------------------------
    |
    */
	
	public function getTrainingList()
	{
		$trainings = ProviderTraining::where('individual_id', NULL)->where('provider_id', Auth::user()->provider_id)->get();
		if(Auth::user()->hasGroupType('provider', ['Administrator', 'Manager', 'Supervisor'])) {
			$consumer_specific_trainings = ProviderTraining::where('individual_id', '!=', NULL)->where('provider_id', Auth::user()->provider_id)->get();
		}
		else {
			$user = User::with('current_houses.individuals')->where('id', Auth::id())->firstOrFail();
			$individuals = collect([]);
			foreach($user->current_houses AS $house) {
				foreach($house->individuals AS $individual) {
					$individuals->push($individual);
				}
			}
			$consumer_specific_trainings = ProviderTraining::whereIn('individual_id', $individuals->pluck('id'))->where('provider_id', Auth::user()->provider_id)->get();
		}
		return view('training.list', ['trainings' => $trainings, 'consumer_specific_trainings' => $consumer_specific_trainings]);
	}
	
	public function getAddTraining()
	{
		$individuals = ProviderIndividual::where('provider_id', Auth::user()->provider_id)->get();
		return view('training.add', ['individuals' => $individuals]);
	}
	
	public function postAddTraining(Request $request)
	{
		$this->validate($request, [
			'description' => 'max:250',
			'website' => 'max:250',
		], array());
		
		$input = $request->all();

		$questions = array();
		$question_number = 0;
		$response_number = 0;
		foreach($input AS $key => $value) {
			if(strpos($key, "question") !== false) {
				$question_number = ltrim($key, "question_");
				$questions[$question_number]['text'] = trim($value);
			}
			if(strpos($key, "type") !== false) {
				$question_number = ltrim($key, "type_");
				$questions[$question_number]['type'] = trim($value);
			}
			if(strpos($key, "response") !== false) {
				$explode = explode('_', $key);
				$question_number = ltrim($explode[0], "q");
				$response_number = ltrim($explode[1], "response");
				$questions[$question_number]['responses'][$response_number] = trim($value);
			}
			if(strpos($key, 'q'.$question_number) !== false && strpos($key, "correctanswer") !== false) {
				$explode = explode('_', $key);
				$question_number = ltrim($explode[0], "q");
				$response_number = ltrim($explode[1], "correctanswer");				
				$questions[$question_number]['correct'][$response_number] = true;
			}
		}
		
		$training = ProviderTraining::create([
			'provider_id' => Auth::user()->provider_id,
			'individual_id' => $input['individual'] != '0' ? decrypt($input['individual']) : NULL,
            'title' => trim($input['title']),
            'description' => trim($input['description']),
            'website' => trim($input['website'])
        ]);
		
		foreach($questions AS $q_num => $question) {
			$training_question = ProviderTrainingQuestion::create([
				'training_id' => $training->id,
				   'question' => $question['text'],
				   'type' => $question['type']
			]);
			foreach($question['responses'] AS $r_num => $response) {
				$answer = ProviderTrainingQuestionAnswer::create([
					'question_id' => $training_question->id,
					'answer' => $response,
					'correct' => isset($questions[$q_num]['correct'][$r_num]) ? 1 : 0
				]);
			}
		}

		return redirect()->back()->with('message', 'Training Added.');
	}
	
	public function getEditTraining($id)
	{
		$training = Training::where('id', decrypt($id))->where('provider_id', Auth::user()->provider_id)->get();
		return view('training.edit', ['training' => $training]);
	}
	
	public function postEditTraining(Request $request, $id)
	{
		$this->validate($request, [
			'title' => 'required|max:50',
			'description' => 'max:250',
			'website' => 'max:250',
		], array());
		
		$training = ProviderTraining::where('id', decrypt($id))->firstOrFail();
		$training->title = trim($input['title']);
		$training->description = trim($input['description']);
		$training->website = trim($input['website']);
		$training->save();
		
		return redirect()->to('training/list')->with('message', 'Training Updated.');
	}
		
	public function getTrainingTake($id) 
	{
		$training = ProviderTraining::with('questions.answers')->where('id', decrypt($id))->where('provider_id', Auth::user()->provider_id)->first();
		
		return view('training.view', ['training' => $training]);
	}
	
	public function postTrainingTake(Request $request, $id)
	{
		$training = ProviderTraining::with('questions.answers')->where('id', decrypt($id))->where('provider_id', Auth::user()->provider_id)->first();
		
		$input = $request->all();
		
		$correct = 0;
		foreach($training->questions AS $question) {
			$user_answer = $input['q_'.$question->id];
			if($question->type == 'dropdown') {
				foreach($question->answers AS $answer) {
					if($user_answer == $answer->id && $answer->correct == 1) {
						$correct++;
					}
				}
			}
			if($question->type == 'checkbox') {
				
				$user_correct = $question->answers->where('correct', 1)->whereIn('id', $user_answer);
				$question_correct = $question->answers->where('correct', 1);				
				if(count($user_answer) == $user_correct->count() && $user_correct->count() == $question_correct->count()) {
					$correct++;
				}
				
			}
        }
        $question_count = $training->questions->count() > 0 ? $training->questions->count() : 1;
		$score = $correct/$question_count*100;
		
		$user_training = ProviderTrainingUser::create([
			'training_id' => $training->id,
			'user_id' => Auth::id(),
			'individual_id' => $training->individual_id != NULL ? $training->individual_id : NULL,
            'score' => $score,
        ]);
        
		return redirect()->to('training/list')->with('message', 'Training Complete with a score of '. $score . '.');
	}
}

resources/views/training/add.blade.php
@extends('layouts.master.master')

@section('title', 'Training')


@section('content')
    <!-- begin #content -->
	<div id="content" class="content">
		<!-- begin breadcrumb -->
		<ol class="breadcrumb pull-right">
			<li><a href="/training/list">Training</a></li>
		</ol>
		<!-- end breadcrumb -->
		<!-- begin page-header -->
		<h1 class="page-header">Training <small>Compliance Documentor</small></h1>
		<!-- end page-header -->
				
		@include('includes.error.list')
		
		<div class="row">
		<form action="" method="POST">
			<div class="col-md-6">
				<!-- begin panel -->
				<div class="panel panel-inverse">
					<div class="panel-body">
					
						<input type="hidden" name="_token" value="{{ csrf_token() }}" />
						<fieldset>
							<legend>Training Add</legend>
							<div class="form-group">
								<a class="btn btn-success training_type collapse" id="make_regular">Make Employee Training</a>
								<a class="btn btn-success training_type" id="make_individual">Make Individual Specific</a>
							</div>
							<div class="form-group training_type collapse">
								<label for="title">For Specific Individual</label>
								<select name="individual" id="individual_select" class="form-control">
									<option value="0">Please Select</option>
									@foreach($individuals AS $k => $individual)
									<option value="{{encrypt($individual->id)}}">{{$individual->first_name}} {{$individual->last_name}}</option>
									@endforeach
								</select>
							</div>
							<div class="form-group training_type">
								<label for="title">Title</label>
								<input type="text" name="title" class="form-control" placeholder="Title" value="{{ old('title') }}"/>
							</div>
							<div class="form-group">
								<label for="description">Description</label>
								<textarea type="text" name="description" class="form-control" placeholder="Description">{{ old('description') }}</textarea>
							</div>
							<div class="form-group">
								<label for="website">Website/Link</label>
								<input type="text" name="website" length="250" class="form-control" placeholder="Website/Link" value="{{ old('website') }}"/>
							</div>
							<button type="submit" class="btn btn-sm btn-primary m-r-5">Save Training</button>
						</fieldset>
						
					</div>
				</div>
				<!-- end panel -->
			</div>
			<!-- end col-6 -->
			<div class="col-md-6">
				<div class="panel panel-inverse" data-sortable-id="form-stuff-3">
					<div class="panel-body">
						<fieldset>
							<legend>Questions</legend>
							<div class="form-group">
								<a class="add_question btn btn-sm btn-success">Add Question</a>
								<div class="row"><ol id="question_list"></ol></div>
							</div>
						</fieldset>
					</div>
				</div>
			</div>		
			<!-- end col-6 -->
		</form>
		</div>
	</div>
	<!-- end #content -->
<script>
$('#make_individual').click(function () {
	$('.training_type').toggle();
});
$('#make_regular').click(function () {
	$('.training_type').toggle();
	$('#individual_select').val(0);
});
var question_counter = 1;
var response_counter = 1;
$('.add_question').click(function () {
	question_counter++;
	$('#question_list').append('<div class="row p-5 form-inline border"><div class="col-lg-6 col-md-6 col-sm-6 form-group">' + 
									'<li><input type="text" name="question_' + question_counter  + '" class="form-control" placeholder="Question Text" value=""/>' +
									'<select name="type_' + question_counter + '" class="form-control">' +
										'<option value="dropdown">Dropdown</option>' +
										'<option value="checkbox">Checkbox</option>' +
										'<option value="textarea">Textbox</option>' +
									'</select>' +
									'<a class="btn btn-xs btn-danger remove_question"><i class="fa fa-times"></i></a></li></div>' + 
									'<div class="col-lg-6 col-md-6 col-sm-6 form-group"><a class="btn btn-sm btn-success add_response" question="' + question_counter  + '">Add Response <i class="fa fa-plus"></i></a></div>' + 
								'</div>');
});
$(document).on('click', '.add_response', function () {
	response_counter++;
	$(this).parent().parent().children("div:nth-child(2)").append('<div class="p-5"><input type="text" name="q' + $(this).attr("question") + '_response' + response_counter + '" class="form-control" placeholder="Response Text" value=""/>' +
										'Correct Response: <input type="checkbox" name="q' + $(this).attr("question") + '_correctanswer' + response_counter + '" class="form-control" value="1"/>' +
										'<a class="btn btn-sm btn-danger remove_response">Remove Response <i class="fa fa-times"></i></a>' + 
										'</div>');
});
$(document).on('click', '.remove_question', function() {
	$(this).parent().parent().parent().remove();
});
$(document).on('click', '.remove_response', function() {
	$(this).parent().remove();
});
</script>
@stop

resources/views/training/edit.blade.php
@extends('layouts.master.master')

@section('title', 'Training')


@section('content')
    <!-- begin #content -->
	<div id="content" class="content">
		<!-- begin breadcrumb -->
		<ol class="breadcrumb pull-right">
			<li><a href="/">Training</a></li>
		</ol>
		<!-- end breadcrumb -->
		<!-- begin page-header -->
		<h1 class="page-header">{{ $training->title }}</h1>
		<!-- end page-header -->
				
		@include('includes.error.list')
		
		<div class="row">
			<div class="col-md-6">
				<!-- begin panel -->
				<div class="panel panel-inverse" data-sortable-id="form-stuff-3">
					<div class="panel-body">
						<form action="" method="POST">
							<input type="hidden" name="_token" value="{{ csrf_token() }}" />
							<fieldset>
								<legend>Training Edit</legend>
								<div class="form-group">
									<label for="title">Title</label>
									<input type="text" name="title" class="form-control" placeholder="Title" value="{{ old('title', $training->title) }}"/>
								</div>
								<div class="form-group">
									<label for="description">Description</label>
									<textarea type="text" name="description" class="form-control" placeholder="Description">
										{{ old('description', $training->description) }}
									</textarea>
								</div>
								<div class="form-group">
									<label for="website">Website/Link</label>
									<input type="text" name="website" class="form-control" placeholder="Website/Link" value="{{ old('website', $training->website) }}"/>
								</div>
								<div class="form-group">
									<legend>Questions</legend>
									<div id="question_list">No Quesitons Added</div>
								</div>
								<button type="submit" class="btn btn-sm btn-primary m-r-5">Save</button>
							</fieldset>
						</form>
					</div>
				</div>
				<!-- end panel -->
			</div>
			<!-- end col-6 -->		
		</div>
	</div>
	<!-- end #content -->

<script>
$('#zip').mask('99999');
</script>
@stop

resources/views/training/view.blade.php
@extends('layouts.master.master')

@section('title', 'Training')


@section('content')
    <!-- begin #content -->
	<div id="content" class="content">
		<!-- begin breadcrumb -->
		<ol class="breadcrumb pull-right">
			<li><a href="/training/list">Training List</a></li>
		</ol>
		<!-- end breadcrumb -->
		<!-- begin page-header -->
		<h1 class="page-header">Training {{ $training->title }}</h1>
		<!-- end page-header -->
		
		@include('includes.error.list')
		
		<div class="row">
			<div class="col-md-6">
				<div class="panel panel-success">
					<div class="panel-heading">
						<h4 class="panel-title">{{ $training->title_name }}</h4>
					</div>
					<div class="panel-body">
						<form method="POST" class="form" action="">
							<input type="hidden" name="_token" value="{{ csrf_token() }}"  />
							<fieldset>
							@foreach($training->questions AS $question)						
								@if($question->type == 'textbox')
								<div class="form-group">
									<label for="first_name">{{$question->question}}</label>
									<input type="text" name="q_{{$question->id}}" class="form-control" value="{{ old('q_'.$question->id) }}" />
								</div>
								@endif
								@if($question->type == 'dropdown')
								<div class="form-group">
									<label for="first_name">{{$question->question}}</label>
									<select name="q_{{$question->id}}" class="form-control">
										<option value="">Please Select</option>
										@foreach($question->answers AS $answer)
											<option value="{{$answer->id}}">{{$answer->answer}}</option>
										@endforeach
									</select>
								</div>
								@endif
								@if($question->type == 'checkbox')
								<div class="form-group">
									<label for="first_name">{{$question->question}}</label><br />
									@foreach($question->answers AS $answer)
										<label><input type="checkbox" name="q_{{$question->id}}[]" class="" value="{{$answer->id}}" /> {{$answer->answer}}</label><br />
									@endforeach
								</div>
								@endif
							@endforeach
							<button type="submit" class="btn btn-sm btn-primary m-r-5">Complete Training</button>
						</form>
					</div>
				</div>
			</div>			
		</div>
	</div>
	<!-- end #content -->
@stop